17-10-2020 16:12:24-- [21] --Traceback (most recent call last):
  File "POC.py", line 89, in init
    check(next, 0)
  File "POC.py", line 137, in check
    start(batchid)
  File "POC.py", line 150, in start
    cycle_time(df_orders, batchID)
  File "POC.py", line 203, in cycle_time
    planning(df_cycle_complete, start_date, finish_date, batchID)
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\planning.py", line 131, in planning
    machines[in_machine[order].machines].first(in_machine[order])  # Plan the order on the work center
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 92, in first
    product.combined = order_combined_orders(product.combined, addcolor(product.id), product.insert,
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 354, in order_combined_orders
    combined_products = product.combined                # List of products with the same mould
AttributeError: 'list' object has no attribute 'combined'

17-10-2020 16:12:41-- [22] --Traceback (most recent call last):
  File "POC.py", line 89, in init
    check(next, 0)
  File "POC.py", line 137, in check
    start(batchid)
  File "POC.py", line 150, in start
    cycle_time(df_orders, batchID)
  File "POC.py", line 203, in cycle_time
    planning(df_cycle_complete, start_date, finish_date, batchID)
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\planning.py", line 131, in planning
    machines[in_machine[order].machines].first(in_machine[order])  # Plan the order on the work center
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 92, in first
    product.combined = order_combined_orders(product.combined, addcolor(product.id), product.insert,
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 354, in order_combined_orders
    combined_products = product.combined                # List of products with the same mould
AttributeError: 'list' object has no attribute 'combined'

17-10-2020 17:56:36-- [28] --Traceback (most recent call last):
  File "POC.py", line 89, in init
    check(next, 0)
  File "POC.py", line 137, in check
    start(batchid)
  File "POC.py", line 150, in start
    cycle_time(df_orders, batchID)
  File "POC.py", line 203, in cycle_time
    planning(df_cycle_complete, start_date, finish_date, batchID)
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\planning.py", line 145, in planning
    machines[j].add(products[product])  # Add to order to be scheduled in the work center
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 170, in add
    product.combined = order_combined_orders(product, addcolor(product.id), old_insert, comb_orders)
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 423, in order_combined_orders
    print(df_combined_orders['Order'].order)
  File "C:\Users\BFonv\anaconda3\envs\Nimble\lib\site-packages\pandas\core\generic.py", line 5130, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'order'

17-10-2020 18:11:04-- [30] --Traceback (most recent call last):
  File "POC.py", line 89, in init
    check(next, 0)
  File "POC.py", line 137, in check
    start(batchid)
  File "POC.py", line 150, in start
    cycle_time(df_orders, batchID)
  File "POC.py", line 203, in cycle_time
    planning(df_cycle_complete, start_date, finish_date, batchID)
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\planning.py", line 145, in planning
    machines[j].add(products[product])  # Add to order to be scheduled in the work center
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 170, in add
    product.combined = order_combined_orders(product, addcolor(product.id), old_insert, comb_orders)
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 441, in order_combined_orders
    comb_orders = order_combined_orders(first, old_color, old_insert, comb_orders)
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 385, in order_combined_orders
    if len(prod.insert) == len(old_insert):
TypeError: object of type 'numpy.int64' has no len()

17-10-2020 18:16:05-- [31] --Traceback (most recent call last):
  File "C:\Users\BFonv\anaconda3\envs\Nimble\lib\site-packages\pandas\core\indexes\base.py", line 2889, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 97, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "POC.py", line 89, in init
    check(next, 0)
  File "POC.py", line 137, in check
    start(batchid)
  File "POC.py", line 150, in start
    cycle_time(df_orders, batchID)
  File "POC.py", line 203, in cycle_time
    planning(df_cycle_complete, start_date, finish_date, batchID)
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\planning.py", line 145, in planning
    machines[j].add(products[product])  # Add to order to be scheduled in the work center
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 170, in add
    product.combined = order_combined_orders(product, addcolor(product.id), old_insert, comb_orders)
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 441, in order_combined_orders
    comb_orders = order_combined_orders(first, old_color, old_insert, comb_orders)
  File "C:\Users\BFonv\OneDrive\Bureaublad\Nimble\KeeeperAI-Operational-Concept\classes.py", line 412, in order_combined_orders
    impact = df_color.loc[str(new_color)][str(old_color)]  # Get the impact of the color change
  File "C:\Users\BFonv\anaconda3\envs\Nimble\lib\site-packages\pandas\core\series.py", line 882, in __getitem__
    return self._get_value(key)
  File "C:\Users\BFonv\anaconda3\envs\Nimble\lib\site-packages\pandas\core\series.py", line 991, in _get_value
    loc = self.index.get_loc(label)
  File "C:\Users\BFonv\anaconda3\envs\Nimble\lib\site-packages\pandas\core\indexes\base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: '0'

